---
- name: Add 1Password APT repository
  ansible.builtin.deb822_repository:
    name: 1password
    types: [deb]
    uris: https://downloads.1password.com/linux/debian/amd64
    suites: stable
    components: [main]
    signed_by: https://downloads.1password.com/linux/keys/1password.asc
  notify: apt-update

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Install 1Password
  ansible.builtin.apt:
    name: 1password
    state: present
