[all:vars]
ansible_python_interpreter=/usr/bin/python3

[local_desktop:vars]
ansible_become=true
ansible_connection=local
ansible_become_exe=/usr/bin/sudo.ws
is_server=false

[local_desktop]
localhost

[servers:vars]
ansible_become=true
is_server=true

[servers]
