---
- name: Test
  hosts: local
  become: true
  vars_files:
    - ./variables.yml
  handlers:
    - name: apt-update
      ansible.builtin.apt:
        update_cache: true
  roles:
    #- common
    - ssh_key
    #- git
    #- php
    #- docker
    #- vscode
    #- chrome
    #- firefox

    #- system-upgrade
    #- snap-update

    #
    # - node
