---
- name: Test
  hosts: local
  become: true
  vars_files:
    - ./variables.yml
  roles:
    - common
    #- git
    #- php
    # - firefox
    # - chrome
    # - vscode
    # - docker

    # - node

