---
- name: Install development tools for desktop
  hosts: local_desktop
  become: true
  vars_files:
    - ./variables.yml
  handlers:
    - name: apt-update
      ansible.builtin.apt:
        update_cache: true
  roles:
    # Debug dynamic variables
    - debug

    # System packages
    - common
    - auto-updates

    # Development
    - ssh_key
    - git
    - php
    - node
    - docker
    - vscode

    # Optional
    - virtualbox
    - onepassword

    # Browsers
    - chrome
    - firefox

    # Finally upgrade the system and snap packages
    - system-upgrade
    - snap-update
