---

#####################################
#
# PUBLIC REPO - DONT USE SECRETS HERE
#
#####################################

workstation_user: "{{ lookup('ansible.builtin.env', 'USER') }}"
workstation_home: "/home/{{ workstation_user }}"

ssh_key_comment: "{{ workstation_user }}@{{ ansible_facts.hostname }} (ansible {{ ansible_facts.date_time.date }})"
# add public key to github: https://github.com/settings/ssh/new
# add public key to gitlab: https://gitlab.com/-/user_settings/ssh_keys

# https://github.com/settings/emails
git_user_email: "10514742+rboonzaijer@users.noreply.github.com"
git_user_name: "Roel"

nvm_version: "v0.40.5"
node_version: "--lts"

php_version: "8.5"

apt_architecture: "amd64"

virtualbox_package: virtualbox-7.2
