---
- name: Add Visual Studio Code repository
  ansible.builtin.deb822_repository:
    name: vscode
    types: [deb]
    uris: https://packages.microsoft.com/repos/code
    suites: stable
    components: [main]
    architectures: ["{{ apt_architecture }}"]
    signed_by: https://packages.microsoft.com/keys/microsoft.asc
  notify: apt-update

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Install Visual Studio Code
  ansible.builtin.apt:
    name: code
    state: present
