---
- name: Install Git
  ansible.builtin.apt:
    name: git
    state: present

- name: Configure Git user name
  become: true
  become_user: "{{ workstation_user }}"
  ansible.builtin.command:
    cmd: git config --global user.name "{{ git_user_name }}"
  environment:
    HOME: "{{ workstation_home }}"
  changed_when: false

- name: Configure Git email
  become: true
  become_user: "{{ workstation_user }}"
  ansible.builtin.command:
    cmd: git config --global user.email "{{ git_user_email }}"
  environment:
    HOME: "{{ workstation_home }}"
  changed_when: false

- name: Configure Git default branch
  become: true
  become_user: "{{ workstation_user }}"
  ansible.builtin.command:
    cmd: git config --global init.defaultBranch main
  environment:
    HOME: "{{ workstation_home }}"
  changed_when: false

- name: Configure Git automatic line endings
  become: true
  become_user: "{{ workstation_user }}"
  ansible.builtin.command:
    cmd: git config --global core.autocrlf input
  environment:
    HOME: "{{ workstation_home }}"
  changed_when: false