---
- name: Add Google Chrome repository
  ansible.builtin.deb822_repository:
    name: google-chrome
    types: [deb]
    uris: https://dl.google.com/linux/chrome/deb/
    suites: [stable]
    components: [main]
    architectures: ["{{ apt_architecture }}"]
    signed_by: https://dl.google.com/linux/linux_signing_key.pub
  notify: apt-update

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Install Google Chrome
  ansible.builtin.apt:
    name: google-chrome-stable
    state: present
