---
- name: Install NVM dependencies
  ansible.builtin.apt:
    name:
      - build-essential
      - curl
      - git
    state: present

- name: Clone NVM
  become: true
  become_user: "{{ workstation_user }}"
  ansible.builtin.git:
    repo: https://github.com/nvm-sh/nvm.git
    dest: "{{ workstation_home }}/.nvm"
    version: "{{ nvm_version }}"
    update: true

- name: Add NVM configuration to Bash
  become: true
  become_user: "{{ workstation_user }}"
  ansible.builtin.blockinfile:
    path: "{{ workstation_home }}/.bashrc"
    create: true
    marker: "# {mark} ANSIBLE MANAGED NVM"
    block: |
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

- name: Check if latest Node.js LTS is installed
  become: true
  become_user: "{{ workstation_user }}"
  ansible.builtin.shell:
    cmd: |
      export NVM_DIR="{{ workstation_home }}/.nvm"
      . "$NVM_DIR/nvm.sh"

      installed_version="$(nvm version 'lts/*')"
      remote_version="$(nvm version-remote --lts)"

      [ "$installed_version" = "$remote_version" ]
    executable: /bin/bash
  environment:
    HOME: "{{ workstation_home }}"
  register: node_installed
  failed_when: false
  changed_when: false

- name: Install latest Node.js LTS
  become: true
  become_user: "{{ workstation_user }}"
  ansible.builtin.shell:
    cmd: |
      set -e
      export NVM_DIR="{{ workstation_home }}/.nvm"
      . "$NVM_DIR/nvm.sh"

      nvm install --lts
      nvm alias default 'lts/*'
      nvm use default
      corepack enable
    executable: /bin/bash
  environment:
    HOME: "{{ workstation_home }}"
  when: node_installed.rc != 0
