---
- name: Update APT cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Finish interrupted package configuration
  ansible.builtin.command:
    cmd: dpkg --configure -a
  become: true
  changed_when: false

- name: Install common packages
  ansible.builtin.apt:
    name:
      - bash-completion
      - build-essential
      - ca-certificates
      - curl
      - gpg
      - htop
      - jq
      - less
      - net-tools
      - openssh-client
      - software-properties-common
      - tree
      - rsync
      - unzip
      - wget
      - zip
    state: present
