---
# https://docs.docker.com/engine/install/ubuntu/

- name: Remove conflicting Docker packages
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-compose
      - docker-compose-v2
      - docker-doc
      - podman-docker
      - containerd
      - runc
    state: absent

- name: Add Docker repository
  ansible.builtin.deb822_repository:
    name: docker
    uris: https://download.docker.com/linux/ubuntu
    suites: "{{ ansible_facts.distribution_release }}"
    components: [stable]
    types: [deb]
    signed_by: https://download.docker.com/linux/ubuntu/gpg
    architectures: ["{{ apt_architecture }}"]
    state: present
  notify: apt-update

- name: Check if notifiers were called - call handlers if requied - apt-update
  ansible.builtin.meta: flush_handlers

- name: Install Docker packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Enable and start Docker
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started

- name: Add workstation user to Docker group
  ansible.builtin.user:
    name: "{{ workstation_user }}"
    groups:
      - docker
    append: true

- name: Inform user
  ansible.builtin.debug:
    msg: >
      {{ workstation_user }} has been added to the docker group.
      Log out and back in before using Docker without sudo.

      To activate the new group in the current shell without logging out, run:
        newgrp docker
