---
- name: Add PHP repository
  ansible.builtin.apt_repository:
    repo: ppa:ondrej/php
    state: present

- name: Update APT cache
  ansible.builtin.apt:
    update_cache: true

- name: Install PHP
  ansible.builtin.apt:
    name:
      - "php{{ php_version }}"
      - "php{{ php_version }}-bcmath"
      - "php{{ php_version }}-cli"
      - "php{{ php_version }}-common"
      - "php{{ php_version }}-curl"
      - "php{{ php_version }}-fpm"
      - "php{{ php_version }}-gd"
      - "php{{ php_version }}-intl"
      - "php{{ php_version }}-mbstring"
      - "php{{ php_version }}-mysql"
      - "php{{ php_version }}-opcache"
      - "php{{ php_version }}-readline"
      - "php{{ php_version }}-soap"
      - "php{{ php_version }}-sqlite3"
      - "php{{ php_version }}-xml"
      - "php{{ php_version }}-zip"
    state: present

- name: Enable and start PHP-FPM
  ansible.builtin.systemd:
    name: "php{{ php_version }}-fpm"
    enabled: true
    state: started

- name: Download Composer installer
  ansible.builtin.get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-setup.php
    mode: "0644"

- name: Install Composer
  ansible.builtin.command:
    cmd: php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
    creates: /usr/local/bin/composer