---
# - name: Add PHP repository
#   ansible.builtin.apt_repository:
#     repo: ppa:ondrej/php
#     state: present
#
# - name: Update APT cache
#   ansible.builtin.apt:
#     update_cache: true


# Release names: https://releases.ubuntu.com/
- name: Add Ondřej PHP repository
  ansible.builtin.deb822_repository:
    name: ondrej-php
    types: [deb]
    uris: https://ppa.launchpadcontent.net/ondrej/php/ubuntu
    #suites: "{{ ansible_distribution_release }}"
    suites: "{{ ansible_facts.distribution_release }}"
    components: [main]
    signed_by: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x4F4EA0AAE5267A6C
    state: >-
      {{
        'present'
        if ansible_facts.distribution == 'Ubuntu'
        and ansible_facts.distribution_release in ['jammy', 'noble']
        else 'absent'
      }}
  notify: apt-update

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

# - name: Update apt cache
#   ansible.builtin.apt:
#     update_cache: true

- name: Install PHP
  ansible.builtin.apt:
    name:
      - "php{{ php_version }}"
      - "php{{ php_version }}-bcmath"
      - "php{{ php_version }}-cli"
      - "php{{ php_version }}-common"
      - "php{{ php_version }}-ctype"
      - "php{{ php_version }}-curl"
      - "php{{ php_version }}-fpm"
      - "php{{ php_version }}-gd"
      - "php{{ php_version }}-intl"
      - "php{{ php_version }}-iconv"
      - "php{{ php_version }}-imagick"
      - "php{{ php_version }}-mbstring"
      - "php{{ php_version }}-mysql"
      - "php{{ php_version }}-readline"
      - "php{{ php_version }}-sqlite3"
      - "php{{ php_version }}-xml"
      - "php{{ php_version }}-zip"
    state: present

# opcache is part of php as of 8.5
- name: Install PHP OPcache
  ansible.builtin.apt:
    name:
    - "php{{ php_version }}-opcache"
    state: present
  when: php_version is version('8.5', '<')

# - name: Enable and start PHP-FPM
#   ansible.builtin.systemd:
#     name: "php{{ php_version }}-fpm"
#     enabled: true
#     state: started

- name: Download Composer installer
  ansible.builtin.get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-setup.php
    mode: "0644"

- name: Install Composer
  ansible.builtin.command:
    cmd: php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
    creates: /usr/local/bin/composer
